# Build stage
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests

# Final stage
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/airports*.jar /app/airports.jar
EXPOSE 8080
CMD ["java", "-jar", "airports.jar"]